---

# Note: changing keyfilename will break vagrant provisioning if not updated Vagrantfile's in this project
public_key: "~/.ssh/id_ed25519_infadmin.pub"
private_key: "~/.ssh/id_ed25519_infadmin"

# Infrastructure
dns:
  - 10.10.3.53
  - 10.10.3.153
timezone: Australia/Brisbane
search_domain: dazzathewiz.com

# networks are configured in unifi controller
networks:
  network_services:
    subnet: 10.10.3.0/24
    gateway: 10.10.3.1
    vlan: 903

# Logging and Metrics
influx_server: 10.10.1.101
influx_port: 80
influx_organization: homelab.local
influx_v1_server: 10.10.1.101
influx_v1_port: 8086

# Container defaults
docker_dir: /opt/docker/data

# Ceph defaults
default_ceph_conf: /etc/ceph/ceph.conf

# Virtual Machine defaults
provisioning_user: infadmin

# System defaults
enable_powersaving: true
