---

# Chia Main farmer variables only

# List the 1Password items to grab the seed phrases from for chia nmemonics
chia_farmer_mnemonics:
  - name: "Chia (XCH) Farming Wallet"
    field: "recovery seed phrase"
    vault: "Chia Mining"

chia_farmer_container_keys_dir: /root/keys

containers:
  ###
  - service_name: machinaris
    active: true
    image: ghcr.io/guydavis/machinaris
    container_name: machinaris
    hostname: "{{ inventory_hostname }}"
    restart: always
    volumes: 
      - "{{ chia_machinaris_data }}/.machinaris:/root/.chia"
      - "{{ chia_machinaris_data }}/keys:{{ chia_farmer_container_keys_dir }}"
      # Volumes are set by `role: chia`, where the host has `chia_harvester_plots` defined, otherwise define:
      # - "/host/path/1:/plots1"
      # - "/host/path/2:/plots2"
      # - "/host/path/3:/plots3"
    environment: 
      - "TZ={{ timezone }}"
      - mode=fullnode
      - "worker_address={{ chia_network['chia_main']['ip'] }}"
      # These options are set by `role: chia`, where the host has `chia_harvester_plots` and/or `chia_farmer_mnemonics` defined
      # - "plots_dir=/plots1:/plots2:/plots3
      # - "keys=/root/.chia/mnemonic.txt:/root/.chia/fil_mnemonic_1.txt"
      - blockchains=chia
      - blockchain_db_download=true
      - OPENCL_GPU=nvidia
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    # network_mode: "host"
    networks:
      miner_network:
        ipv4_address: "{{ chia_network['chia_main']['ip'] }}"
    ports:
      - 8926:8926
      - 8927:8927
      - 8444:8444
      - 8447:8447
    
docker_networks:
  miner_network:
    driver: macvlan
    driver_opts:
      parent: "{{ ansible_default_ipv4.interface }}"
    ipam:
      config:
        - subnet: "{{ chia_network['default']['subnet'] }}"
          gateway: "{{ chia_network['default']['gateway'] }}"
          ip_range: "{{ chia_network['default']['ip_range'] }}"
