---

- name: Register the docker group id
  shell: stat -c '%g' /var/run/docker.sock
  register: docker_gid
  changed_when: false

- name: Apply specific profile {{ profile }}
  block:
    - name: Import vars for {{ profile }}.yml
      include_vars: "{{ profile }}.yml"
    - name: Update inputs defaults
      set_fact:
        telegraf_plugins_default: "{{ lookup('vars', 'telegraf_plugins_' + profile) }}" 
  when: profile != ""

- name: Copy telegraf.conf
  become: yes
  template:
    src: "telegraf.conf.j2"
    dest: "{{ docker_dir }}/{{ container_name }}/telegraf.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart container

- name: Make sure the {{ container_name }} container is created and running
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "telegraf:latest"
    pull: yes
    state: 'started'
    user: "telegraf:{{docker_gid.stdout}}"          # See: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
    hostname: "{{ inventory_hostname }}"
    env:
      "TZ": "{{ timezone }}"
      "HOST_ETC": "/hostfs/etc"
      "HOST_PROC": "/hostfs/proc"
      "HOST_SYS": "/hostfs/sys"
      "HOST_VAR": "/hostfs/var"
      "HOST_RUN": "/hostfs/run"
      "HOST_MOUNT_PREFIX": "/hostfs"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/hostfs"
    network_mode: host
    restart_policy: always
    