---
# Get the VM IP address

- name: Get VM IP address
  proxmox_query:
    query: "nodes/{{ pve_host }}/qemu/{{ pve_instance.vmid }}/agent/network-get-interfaces"
  register: _pve_qemu_ip_json

- set_fact:
    _pve_instance_interface: "{{ (_pve_qemu_ip_json | community.general.json_query(query)) }}"
  vars:
    query: "response.result[?name=='eth0']"

- set_fact:
    _pve_instance_ip: "{{ item['ip-address'] }}"
  with_items: "{{ _pve_instance_interface[0]['ip-addresses'] }}"
  when: item['ip-address-type'] == 'ipv4'
