---
- import_tasks: "provision_{{ provision_type }}.yaml"
  tags: provision


# Add provisioned instances to Ansible inventory
- name: Add new instances to inventory
  block:

    # Get instance information if not already present
    - import_tasks: get_pve_instances.yaml
      when: pve_instance is not defined

    # Get the instance IP
    - import_tasks: get_{{ provision_type }}_ip.yaml

    # Setup instance in host file
    - name: Add instance to ansible hosts
      add_host:
        name: "{{ hostvars[item]._pve_instance_ip }}"
        ansible_ssh_user: "{% if provision_type == 'lxc' %}root{% else %}{{ provisioning_user }}{% endif %}"
        ansible_ssh_private_key_file: "{{ private_key }}"
        groups: "{{ provision_inventory_hostgroup }}"
      with_items: "{{ ansible_play_batch }}"
      when: hostvars[item]._pve_instance_ip is defined
      changed_when: false

    - name: Get instance ssh key ready for known_hosts
      shell: ssh-keyscan {{ instance_name }},{{ _pve_instance_ip }}
      register: ssh_known_host_result
      ignore_errors: yes
      retries: 3        # In testing, this keyscan command can fail and not return the key. Not sure why...
      delay: 1
      until: ssh_known_host_result.rc == 0
      delegate_to: localhost
      changed_when: false

    - name: Add/update public key in ssh known_hosts file
      known_hosts:
        name: "{{ instance_name }}"
        key: "{{ ssh_known_host_result.stdout }}"
        path: ~/.ssh/known_hosts
      delegate_to: localhost
      when: ssh_known_host_result.rc == 0
      throttle: 1       # Throttle here b/c even though run on localhost there is a simultaneous task for each host in the play
  
  when: "provision_add_to_inventory | bool"
