---

- name: include template variables from proxmox role
  include_vars: ../proxmox/vars/templates.yml

# Clone VM from template
- name: Cloning virtual machine from "{{ pve_template_name }}" with name "{{ instance_name }}" 
  proxmox_kvm:
    api_user : "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host : "{{ pve_api_host }}"
    name : "{{ instance_name }}"
    node : "{{ pve_host }}"
    clone: "{{ pve_template_name }}"
    vmid: "{{ pve_template_id }}"
    full: yes
    timeout: 300
    storage: "{{ vm_storage|default(omit) }}"
  throttle: 1   # Prevents VMID conflict when cloning from multiple hosts simultaneously
  register: vm

- debug: 
    msg: '{{ vm }}'
  when: vm is defined

- block:
  # Customise the user cloud-init config to include qemu-agent package (can't be done via proxmox cloud-init support)
  - name: Get local storage information
    proxmox_query:
      query: "storage/local"
    register: _pve_storage_local

  - name: Get cloud template USER data
    shell: qm cloudinit dump {{ pve_template_id }} user
    register: _cloudinit_user_config
    changed_when: false

  - name: Copy custom cloud-init for VM {{ instance_name }}
    copy:
      content: "{{ _cloudinit_user_config.stdout + lookup('file','files/cloud-init-package-qemu-agent.yaml') }}"
      dest: "{{ _pve_storage_local.response.path }}/snippets/{{ vm.vmid }}-cloud-init-user.yaml"
    when: vm is defined

  - name: Update VM settings to use custom cloud-init file
    shell: qm set {{ vm.vmid }} --cicustom "user=local:snippets/{{ vm.vmid }}-cloud-init-user.yaml"
    when: vm.changed

  when: vm_install_qemu_agent | bool

- name: Change VM memory if defined
  shell: qm set {{ vm.vmid }} --memory {{ vm_memory }}{% if vm_memory_min is defined %} --balloon {{ vm_memory_min }}{% endif %}
  when: vm_memory is defined and vm.changed

- name: Change VM CPU number if defined
  shell: qm set {{ vm.vmid }} --cores {{ vm_cpu }}
  when: vm_cpu is defined and vm.changed

- name: Increasing disk if it is necessary
  shell: qm resize {{ vm.vmid }} scsi0 +{{ vm_disk_increase }}G
  when: vm_disk_increase != 0 and vm.changed

- name: Apply correct network interface settings
  shell: qm set {{ vm.vmid }} --net0 virtio{% if vm_network_bridge is defined %},bridge={{ vm_network_bridge }}{% else %},bridge=vmbr0{% endif %}{% if vm_network_vlan is defined %},tag={{ vm_network_vlan }}{% endif %}{% if vm_network_mac is defined %},macaddr={{ vm_network_mac }}{% endif %}
  when: vm.changed and vm_network_bridge is defined or vm_network_vlan is defined or vm_network_mac is defined

- name: Set a PCIe device passthrough to the VM if required
  shell: qm set {{ vm.vmid }} -hostpci{{ my_idx }} {% if item['id'] is defined %}{{ item['id'] }}{% else %}{{ item }}{% endif %}{% if item['mdev'] is defined %},mdev={{ item['mdev'] }}{% endif %}{% if item['rombar'] is defined %},rombar={{ item['rombar'] }}{% endif %}
  loop: "{{ vm_pcie_device }}"
  loop_control:
    index_var: my_idx
  when: vm.changed and vm_pcie_device is defined

- name: Setup phyiscal disk passthough
  shell: qm set {{ vm.vmid }} -scsi{{ my_idx + 2 }} /dev/disk/by-id/{{ item }}
  loop: "{{ vm_disk_passthrough }}"
  loop_control:
    index_var: my_idx
  when: (vm_disk_passthrough | length > 0) and vm.changed

- name: Enable qemu agent
  shell: qm set {{ vm.vmid }} --agent 1
  when: vm_enable_agent and vm.changed

- name: Stage VM tags
  set_fact:
    _pve_gui_tags_list: "{{ _pve_gui_tags_list | union(pve_gui_tags_list) }}"
  when: pve_gui_tags_enable

- name: Provision VM tags
  shell: qm set {{ vm.vmid }} --tags {{ _pve_gui_tags_list|join(';') }}
  when: vm.changed and pve_gui_tags_enable

- name: starting new Virtual Machine ID {{ vm.vmid }}
  proxmox_kvm:
    api_user : "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host : "{{ pve_api_host }}"
    vmid: "{{ vm.vmid }}"
    node : "{{ pve_host }}"
    state : started
    timeout: 300
  when: vm is defined and vm_start
