---

- name: Create the container
  community.general.proxmox:
    node: "{{ pve_host }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    proxmox_default_behavior: "{{ pve_default_behavior | default('compatibility') }}"
    validate_certs: "{{ pve_validate_certs | default(omit) }}"
    hookscript: "{{ pve_lxc_hookscript | default(omit) }}"
    ostemplate: "{{ pve_lxc_ostemplate_storage | default('local') }}:{{ pve_lxc_ostemplate_content_type | default('vztmpl') }}/{{ lxc_ostemplate_name if(lxc_ostemplate_name is defined) else ( pve_lxc_ostemplate_url | urlsplit('path') | basename ) }}"
    hostname: "{{ instance_name }}"
    vmid: "{{ pve_lxc_vmid | default(omit) }}"
    description: "{{ pve_lxc_description | default(omit) }}"
    password: "{{ lxc_root_password }}"
    pubkey: "{{ lxc_root_authorized_pubkey | default(omit) }}"
    cores: "{{ pve_lxc_cpu_cores | default(omit) }}"
    cpus: "{{ pve_lxc_cpu_limit | default(omit) }}"
    cpuunits: "{{ pve_lxc_cpu_units | default(omit) }}"
    memory: "{{ pve_lxc_memory | default(omit) }}"
    swap: "{{ pve_lxc_swap | default(omit) }}"
    storage: "{{ lxc_storage | default(omit) }}"
    disk: "{{ pve_lxc_disk | default(omit) }}"
    ip_address: "{{ pve_lxc_ip_address | default(omit) }}"
    mounts: >-
      {   {%- for item in lxc_mounts -%}
            "{{ item.id }}":"{{ item.storage|default('local-lvm') }}:{{ item.size|default(32) }},mp={{ item.mount_point|default('/mnt/mp0') }},{% if item.acl is defined %}{% if (item.acl) %}acl=1{% else %}acl=0{% endif %},{% endif %}{% if item.quota is defined and item.quota %}quota=1,{% endif %}{% if item.read_only is defined and item.read_only %}ro=1,{% endif %}{% if item.backup is defined and item.backup %}backup=1,{% endif %}{% if item.skip_replication is defined and item.skip_replication %}replicate=0{% endif %}",
          {%- endfor -%}  }
    netif: >-
      {   {%- for item in lxc_net_interfaces -%}
            "{{ item.id }}":"name={{ item.name }},bridge={{ item.bridge }},{% if (item.hwaddr is defined) %}hwaddr={{ item.hwaddr }},{% endif %}{% if (item.ip4 is defined and item.ip4 != 'dhcp') %}ip={{ item.ip4 }}/{{ item.netmask4 }},{% elif (item.ip4 is defined and item.ip4 == 'dhcp') %}ip={{ item.ip4 }},{% endif %}{% if (item.gw4 is defined) %}gw={{ item.gw4 }},{% endif %}{% if (item.ip6 is defined) %}ip6={{ item.ip6 }}/{{ item.netmask6 }},{% endif %}{% if (item.gw6 is defined) %}gw6={{ item.gw6 }},{% endif %}{% if (item.firewall is defined and item.firewall) %}firewall=1,{% endif %}{% if (item.rate_limit is defined) %}rate={{ item.rate_limit }},{% endif %}{% if (item.vlan_tag is defined) %}tag={{ item.vlan_tag }}{% endif %}",
          {%- endfor -%}  }
    nameserver: "{{ pve_lxc_nameserver | default(omit) }}"
    searchdomain: "{{ pve_lxc_searchdomain | default(omit) }}"
    onboot: "{{ pve_onboot | default(omit) }}"
    unprivileged: "{{ pve_lxc_unprivileged | default(omit) }}"
    features: "{{ pve_lxc_features | default(omit) }}"
    timeout: "{{ pve_lxc_timeout | default(omit) }}"
    force: "{{ pve_lxc_force | default(omit) }}"
  throttle: 1   # Prevents VMID conflict when cloning from multiple hosts simultaneously
  register: pve_lxc_container_created

- debug:
    var: pve_lxc_container_created
  when: pve_lxc_container_created is defined

- import_tasks: get_pve_instances.yaml
  when:
    - pve_lxc_vmid is not defined
    - pve_lxc_container_created is succeeded

- name: Set variable with the corresponding VMID for the container in case it has not been defined
  ansible.builtin.set_fact:
    pve_lxc_inferred_vmid: "{{ pve_lxc_vmid if (pve_lxc_vmid is defined) else pve_instance.vmid }}"

- name: Ensure the container is turned on
  community.general.proxmox:
    node: "{{ pve_host }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    vmid: "{{ pve_lxc_inferred_vmid }}"
    state: started
  when: (pve_lxc_container_created is not defined) or (pve_lxc_container_created is succeeded)
