---
# All Nodes configuration
all_node_network_bridge: vmbr1
all_node_network_vlan: 901

# Master Nodes
master_node_name: "k3smaster"
master_node_memory: 4096
master_node_cpu: 2
master_node_disk_increase: 16
master_node_storage: "ceph-vm"
master_node_max: 3

# Worker Nodes
worker_node_name: "k3sworker"
worker_node_disk_increase: 46

# List tags for VMs in Proxmox
pve_tags:
  - k3s
