---
# All Nodes configuration
all_node_network_bridge: vmbr1
all_node_network_vlan: 901

# Master Nodes
master_node_name: "k3smaster"
master_node_memory: 4096
master_node_cpu: 2
master_node_disk_increase: 16
master_node_storage: "ceph-vm"
master_node_max: 3

# Worker Nodes
worker_node_name: "k3sworker"
worker_node_disk_increase: 46

# k3s_worker_node_storage: 'local-nvme'

# `lspci` to identify devices to pass through, then specify in host_vars for each host:
# k3s_worker_pcie:
#   - "02:00.0"   # Typically NVME storage
#   - "00:02.0"   # Typically the built in Intel UHD Graphics

# Create additional virtual disks on particular storage ID's
# k3s_worker_virtual_disk:
#   - 'local-zfs:10,format=raw'

# Passthough disks to k3s worker nodes using their /dev/disk/by-id name:
# k3s_worker_disk_passthrough:
#   - ata-ST4000VN000-1H4168_Z301GA45
#   - ata-ST4000VN000-1H4168_Z3054AS0

# These variables are specified per proxmox host in the host_vars:
# worker_node_memory: 36864
# worker_node_cpu: 6
