---
- hosts: k3s_cluster

  #vars_files: group_vars/secret.yml

  roles:
    - vmguest

- hosts: k3s_node

  # Install apt linix-geneic on workers using intel iGPU. i915 module not available in the cloud image (linux-virtual). 
  # Reboot after install and /dev/dri will be present
  # See https://askubuntu.com/questions/1248870/ubuntu-20-04-i915-passthrough-with-libvirt-kvm
  roles:
    - role: system
      vars:
        packages:
          - linux-generic
      tags: setup

- hosts: k3s_master
  roles:
    - role: system
      tags: setup

# Ensure Longhorn hosts have package dependancies installed, and NVME disk initatlised and mounted
# See: https://fredrickb.com/2022/07/24/introducing-longhorn-to-the-homelab/
- hosts: k3s_longhorn_storage
  roles:
    - role: system
      vars:
        packages:
          - nfs-common
          - open-iscsi
        partition_devices: "{{ k3s_longhorn_blockdevices }}"
      tags: longhorn,setup
  tasks:
    - name: Start the systemd service for iscsid if it is not started
      become: yes
      systemd:
        name: iscsid
        enabled: yes
        state: started
      tags: longhorn,setup
