---
- hosts: dietpi_four

  vars_files: group_vars/secret.yml

  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker

    # Overwrite the docker directory to use USB attached storage
    docker_dir: /mnt/3a535c19-aa87-4315-81ce-485651421360/docker/data

  roles:
    - dietpi

    - role: system
      vars:
        mounts:
          # Disk mounts
          - { path: /mnt/3a535c19-aa87-4315-81ce-485651421360, src: UUID=3a535c19-aa87-4315-81ce-485651421360, fstype: ext4, opts: "noatime,lazytime,rw,nofail,noauto,x-systemd.automount" }
      tags: setup
    
    - { role: geerlingguy.pip, become: true, tags: [setup] }
    - role: geerlingguy.docker_arm
      become: true
      vars:
        docker_users:
          - dietpi
        docker_install_compose: no    # Remove later, there was a dep problem at install with bcrypt
      tags: setup

    # Containers
    - { role: containers/portainer, tags: [containers] }
    - { role: containers/portainer_agent, tags: [containers] }

    # Monitoring TIG stack
    - { role: containers/influxdb, tags: [containers] }
    - role: containers/telegraf
      vars:
        influx:
          url: "http://localhost:8086"
          database_name: rpi_monitoring
        telegraf_config_file: rpi-telegraf.conf
      tags: containers

    # PiHole
    - role: containers/pihole
      vars:
        container_network_ip: "{{ dns[1] }}"
        #pihole_gravity_sync: yes
      tags: containers

    # Cyber Power UPS
    - role: containers/upsd
      vars:
        ups_description: "CyberPower 1300VA PFC Sinewave"
      tags:
        - containers
    
    # Shinobi
    - role: containers/shinobi
      vars:
        container_network_ip: 192.168.13.21
      tags: containers
    
    # Watchtower
    - role: containers/watchtower
      vars:
        update_schedule: "0 30 11 * * *"    # Run at 11:30am daily
      tags: containers

