---
- hosts: proxmox

  vars_files: group_vars/secret.yml

  roles:
    - role: proxmox
      vars:
        pve_create_container_templates: yes
        pve_template_recreate: yes
        pve_metrics_servers:
          - name: InfluxDB
            port: "{{ influx_port }}"
            server: "{{ influx_server }}"
            type: influxdb
            bucket: proxmox
            influxdbproto: http
            organization: homelab.local
            token: "{{ influx_proxmox_token }}"
            # use when need to update an existing metric server token:
            #updatetoken: yes
        pve_ceph_enabled: yes
        pve_nfs_enabled: yes
        pve_extra_packages:
          - iperf3

# Disable/comment out if pve_nfs_enabled: no
- hosts: "{{ pve_ganesha_instance_hosts_group }}"
  vars_files: 
    - group_vars/proxmox.yaml
  roles:
    - role: nfs-ganesha
      tags: nfs

- hosts: "{{ pve_lb_instance_hosts_group }}"
  vars_files: 
    - group_vars/proxmox.yaml
  roles:
    - role: haproxy
      vars:
        haproxy_lb_type: tcp
        haproxy_frontend_name: nfs-frontend
        haproxy_backend_name: nfs-backend
        haproxy_backend_port: 2049
        haproxy_backend_servers: "{{ pve_ganesha_instance_hosts_group }}"
      tags: nfs, haproxy
