---

# Replaces fil-miner functions into proxmox VM

# Create VM
- import_playbook: vm_deploy_storecrypt.yml

# Wait for VM to boot properly
- hosts: controlhost
  roles:
    - role: waitboot
      vars:
        host: "{{ hostvars['storecrypt']['ansible_host'] }}"

- hosts: storecrypt
  roles:
    - vmguest


#Install ZFS

#Install 45drives Houston Command Centre
# - ZFS manager
# - Samba 

#Import ZFS pool

#Install monitoring tools
#- 45Drives Alert manager & Prometheus?? (from evernote notes)
#- Monitor drive temps from passthrough PCIe (somehow)
#- ZFS monitoring

#Install and setup MergerFS

#Setup mount points & mount them with fstab

#Install docker (not snap docker!)
#- Docker compose?

#Dockers:
#- machinaris* #Docker compose?
#- scprime
#- silicoin
#- telegraf
#- portainer & agent

# Managing docker
# - How to manage container updates?
# - How to add or change containers in code?