---

# Replaces fil-miner functions into proxmox VM

# Create VM
- import_playbook: vm_deploy_storecrypt.yml

# Wait for VM to boot properly
- hosts: controlhost
  roles:
    - role: waitboot
      vars:
        host: "{{ hostvars['storecrypt']['ansible_host'] }}"

- hosts: storecrypt
  roles:
    - vmguest

    - role: 45drives/repo
      tags: 45drives
    
    - role: system
      vars:
        packages:
          - zfsutils-linux
          - mergerfs
          - samba
          - cifs-utils
          - 45drives-tools
          - cockpit
          - cockpit-file-sharing
      tags: setup

    - role: 45drives/zfs-manager
      tags: setup

    - role: storecrypt

    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ provisioning_user }}"
      tags: setup


#Install monitoring tools
#- 45Drives Alert manager & Prometheus?? (from evernote notes)
#- Monitor drive temps from passthrough PCIe (somehow)
#- ZFS monitoring

#Dockers:
#- machinaris* #Docker compose?
#- scprime
#- silicoin
#- telegraf
#- portainer & agent

# Managing docker
# - How to manage container updates?
# - How to add or change containers in code?