---
- hosts: prox3

  vars_files: group_vars/secret.yml

  roles:

    # Create the VM in proxmox
    - role: proxmox_provision
      vars:
        instance_name: storecrypt
        vm_memory: 10240
        vm_memory_min: 8192
        vm_cpu: 2
        vm_network_bridge: vmbr1
        vm_network_vlan: 115
        vm_network_mac: 26:0d:67:53:2d:2b
        vm_disk_increase: 46
        #vm_pcie_device: ["02:00.0", "01:00.0"]
        vm_disk_passthrough:
          # Chia Disks
          #- ata-ST16000NM000J-2TW103_ZR51RBDP
          #- ata-ST16000NM000J-2TW103_ZR51T3AQ
          - ata-ST16000NM001G-2KK103_WL2094N3
          #- ata-ST16000NM000J-2TW103_ZR51W96J
          #- ata-ST16000NM000J-2TW103_ZR51XQ68
          - ata-ST16000NM001G-2KK103_ZL258KWJ
          - ata-ST16000NM001G-2KK103_ZL219JBX
          - ata-ST16000NM001G-2KK103_ZL20TN0Y
          - ata-ST16000NM001G-2KK103_ZL21QF7Z
          - ata-ST16000NM001G-2KK103_ZL211QMG 
          # Hybrid Disks
          - ata-ST10000VN0004-2GS11L_ZCH0GJST
