---
- hosts: prox3

  vars_files: group_vars/secret.yml

  roles:

    # Create the VM in proxmox
    - role: proxmox_provision
      vars:
        instance_name: storecrypt
        vm_memory: 24576
        vm_memory_min: 8192
        vm_cpu: 4
        vm_network_bridge: vmbr1
        vm_network_vlan: 115
        vm_network_mac: 26:0d:67:53:2d:2b
        vm_disk_increase: 46
        vm_pcie_device: 
          - id: "01:00.0"       # SAS2308 PCI-Express Fusion-MPT SAS-2
            rombar: "0"
          - id: "02:00.0"       # SAS2008 PCI-Express Fusion-MPT SAS-2 [Falcon]
            rombar: "0"

# Wait for VM to boot properly
- hosts: controlhost
  roles:
    - role: waitboot
      vars:
        host: "{{ hostvars['storecrypt']['ansible_host'] }}"
