---

- name: Manage the docker data
  import_tasks: roles/containers/common/tasks/manage_data.yml
  when: container_data_backup

- name: Make sure {{ container_name }} container is created and running
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    pull: yes
    state: 'started'
    ports:
      - 28967:28967/tcp
      - 28967:28967/udp
      - 14002:14002
    env:
      "TZ": "{{ timezone }}"
      "WALLET": "{{ container_storj_wallet }}"
      "EMAIL": "{{ container_storj_email }}"
      "ADDRESS": "{{ container_storj_address }}"
      "STORAGE": "{{ container_storj_storage }}"
    volumes:
      - "{{ container_storj_data }}:/app/config"
      - "{{ container_storj_dbs }}:/app/dbs"
      - "{{ container_storj_identity }}:/app/identity"
    network_mode: bridge
    restart_policy: always

- name: Persist data to backup location with rsync-cron
  include_role: 
    name: rsync-cron
  vars:
    sync_cron_username: "root"
    sync_cron_src_path: "{{ docker_dir }}/{{ container_name }}/"
    sync_cron_dest_url: "{{ container_data_backup_dir }}"
    sync_cron_freq:
      name: "{{ container_name }} persistent data backup"
      hour: "*/2"
  when: container_data_backup
