---
# handlers file for ansible-role-proxmox
- name: restart pvedaemon
  service:
    name: pvedaemon
    state: restarted

- name: restart pveproxy
  service:
    name: pveproxy
    state: restarted

- name: reload ssh server configuration
  ansible.builtin.systemd:
    name: ssh.service
    state: reloaded

- name: restart watchdog-mux
  service:
    name: watchdog-mux
    state: restarted

- name: restart zfs-zed
  service:
    name: zfs-zed
    state: restarted

- name: restart ceph
  # Needs to use the systemd module directly to be able to
  # reload the systemd daemon
  systemd:
    name: ceph.service
    state: restarted
    daemon_reload: true

- name: restart network
  # Could be a ansible module in future
  shell: pvesh set /nodes/{{ inventory_hostname }}/network

- name: restart pve node
  # Not tested: how the graceful reboot functions when setting up a fresh node from scratch. May require ability
  #   to detect a first run install of ceph is complete.
  import_tasks: "{{ 'pve_reboot_graceful.yml' if pve_graceful_reboot | bool else 'pve_reboot_simple.yml' }}"
