---
container_name: telegraf
telegraf_config_file: telegraf.conf
telegraf_features:
  hddtemp: no
  zfs: no
  sensors: no
influx:
  url: "http://{{ influx_v1_server }}:{{ influx_v1_port }}"
  database_name: filecoin
