---

# Hosts configuration
pve_group: proxmox

# REGEX to identify interface of second nic to setup with vmbr1 bridge
# See how proxmox calculates Network Inface Names: https://pve.proxmox.com/wiki/Network_Configuration#_naming_conventions
pve_second_nic_regex: "^enp.*.f0$"

# Cluster configuration
pve_cluster_clustername: "TEST"
pve_cluster_enabled: yes
pve_cluster_ha_groups: []
pve_cluster_addr0: "{{ ansible_default_ipv4.address if ansible_default_ipv4.address is defined else ansible_default_ipv6.address if ansible_default_ipv6.address is defined }}"
# pve_cluster_addr1: "{{ ansible_eth1.ipv4.address }}

# Template configuration
pve_create_templates: true
pve_template_recreate: false   # deletes and re-creates the template

# SSH configuration
pve_manage_ssh: true
pve_ssh_port: 22
