---
- name: Stage packages needed for base PVE installation
  set_fact:
    _pve_install_packages: []
      #- proxmox-ve
      #- open-iscsi
      #- ksm-control-daemon
      #- systemd-sysv

- name: Stage Ceph packages if Ceph is enabled
  set_fact:
    _pve_install_packages: "{{ _pve_install_packages | union(['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse', 'ceph-mgr-dashboard', 'gdisk']) }}"
  when: "pve_ceph_enabled | bool"

- name: Stage any extra packages the user has specified
  set_fact:
    _pve_install_packages: "{{ _pve_install_packages | union(pve_extra_packages) }}"
