---

# Check that all hosts are online and can get facts for clustering to prevent errors
- name: Ensure that facts are present for all cluster hosts
  assert:
    that:
      - "hostvars[item].ansible_facts"
    msg: "Could not load facts for {{ item }}. Please run your playbook against all hosts in {{ pve_group }}."
  with_items: "{{ groups[pve_group] }}"
  when: "pve_cluster_enabled | bool"
  tags: cluster

- import_tasks: load_variables.yml

- import_tasks: pve_setup_config.yml
  tags: setup

- import_tasks: pve_network.yml
  tags: setup, network, ceph

- import_tasks: pve_nfs_attach.yml
  tags: setup, nfs, mounts

- import_tasks: pve_download_iso_images.yml
  tags: update_images, update_iso_images

- import_tasks: pve_download_container_images.yaml
  when: "pve_create_container_templates | bool"
  tags: update_images, update_container_images

- import_tasks: ssh_cluster_config.yml
  when:
    - "pve_manage_ssh | bool and pve_cluster_enabled | bool"
  tags: cluster

- import_tasks: pve_cluster_config.yml
  when: "pve_cluster_enabled | bool"
  tags: cluster

- import_tasks: pve_templates_config.yml
  when: _node_storage_local is defined
  tags: templates

- import_tasks: pve_metrics_server.yml
  tags: setup, metrics

- import_tasks: pve_ceph.yml
  when: "pve_ceph_enabled | bool"
  tags: ceph, setup
