---

# Download latest ISOs into ISO path
- name: Check the NFS ISO share is mounted
  shell: df | grep /mnt/pve/ISO | wc -l
  register: mounted

- name: Check and download ISO images
  get_url:
    url: "{{ item }}"
    tmp_dest: /mnt/pve/ISO/template/iso/
    dest: /mnt/pve/ISO/template/iso/
  with_items:
    - "{{ images }}"
  when: mounted.stdout  != "0"
  run_once: true    # Only do this task on 1 host