---

# Installs nfs-ganesha on ceph hosts to serve Ceph storage via NFS

- name: Create ceph keyring to store keys
  command: 'ceph-authtool --create-keyring /etc/pve/priv/{{ pve_nfs_ceph_keyring }}'
  args:
    creates: '/etc/pve/priv/{{ pve_nfs_ceph_keyring }}'
  when: "inventory_hostname == groups[pve_ceph_mon_group][0] and pve_nfs_create_client_keyring | bool"

- name: Get cluster auth role
  command: 'ceph auth get {{ pve_ceph_nfs_userid }}'
  register: _pve_ceph_auth_nfsganesha
  changed_when: false
  ignore_errors: true
  when: "inventory_hostname == groups[pve_ceph_mon_group][0] and pve_nfs_create_client_keyring | bool"

- name: Generate client keys and specify capabilities
  shell: |
    ceph-authtool /etc/pve/priv/{{ pve_nfs_ceph_keyring }} -n {{ pve_ceph_nfs_userid }} --gen-key
    ceph-authtool -n {{ pve_ceph_nfs_userid }} --cap mds 'allow rw' --cap mon 'allow r' --cap osd 'allow rw' /etc/pve/priv/{{ pve_nfs_ceph_keyring }}
  when: inventory_hostname == groups[pve_ceph_mon_group][0] and _pve_ceph_auth_nfsganesha.failed and pve_nfs_create_client_keyring | bool

- name: Add keys to cluster for {{ pve_group }} hosts
  shell: |
    ceph -k /etc/pve/priv/ceph.client.admin.keyring auth add {{ pve_ceph_nfs_userid }} -i /etc/pve/priv/{{ pve_nfs_ceph_keyring }}
  when: inventory_hostname == groups[pve_ceph_mon_group][0] and _pve_ceph_auth_nfsganesha.failed and pve_nfs_create_client_keyring | bool

# - name: Create ubuntu 20.04 LXC container on {{ pve_group }} hosts
#   include_role: 
#     name: proxmox_provision
#   vars:
#     provision_type: lxc
#     instance_name: "{{ pve_nfs_instance_name }}{{ inventory_hostname[-1] }}"
#     lxc_ostemplate_name: ubuntu-20.04-standard_20.04-1_amd64.tar.gz     # Specify 20.04 as newer not supported/missing deps
#     lxc_net_interfaces:
#       - id: net0
#         name: eth0
#         ip4: "dhcp"
#         bridge: vmbr2
#     pve_lxc_description: Created by ansible.
#     pve_onboot: yes
#     pve_lxc_unprivileged: yes
#     provision_add_to_inventory: true
#     provision_inventory_hostgroup: "{{ pve_ganesha_instance_hosts_group }}"

# Create as VM's for better HA in proxmox
- name: Create ubuntu 20.04 instance on {{ pve_group }} hosts
  include_role: 
    name: proxmox_provision
  vars:
    instance_name: "{{ pve_nfs_instance_name }}{{ inventory_hostname[-1] }}"
    vm_memory: 1024
    vm_cpu: 1
    vm_network_bridge: vmbr2
    vm_disk_increase: 2
    vm_storage: "ceph-vm"
    provision_add_to_inventory: true
    provision_inventory_hostgroup: "{{ pve_ganesha_instance_hosts_group }}"
  when: inventory_hostname[-1] | int <= pve_nfs_instance_count
