---

# Adds packages for no-subscription model, as seen in: https://www.youtube.com/watch?v=GoZaMgEgrHw
- name: Add "no-subscription" apt source
  blockinfile:
    path: /etc/apt/sources.list
    block: |
      # not for production user
      deb http://download.proxmox.com/debian {{ ansible_distribution_release }} pve-no-subscription
  register: update_apt_nosub

- name: Remove "pve-enterprise" apt source
  lineinfile:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "^deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
    line: "# deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
  register: update_apt_enterprise

- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes
  when: update_apt_nosub.changed or update_apt_enterprise.changed

# from: https://forum.proxmox.com/threads/when-to-reboot.29230/
- name: Check if reboot required
  shell:  "[ `ls -tr /boot/initrd* | tail -1 | cut -d '-' -f 2-` != `uname -r` ]"
  register: result
  ignore_errors: true
  failed_when: result == 2
- debug: msg="{{ inventory_hostname }} needs reboot"
  when: result.rc == 0
- name: Reboot if required
  reboot:
  when: result.rc == 0


# Identify the processor manufacturer by looking for "Intel" or "AMD"
# in `/proc/cpuinfo`.
- name: check if Intel processor
  command: grep -q Intel /proc/cpuinfo
  ignore_errors: true
  register: is_intel
  failed_when: is_intel == 2

- name: check if AMD processor
  command: grep -q AMD /proc/cpuinfo
  ignore_errors: true
  register: is_amd
  failed_when: is_amd == 2

# IOMMU needs to be enabled but note Linux enables differently between Bootmanagers
# GRUB and SYSTEMD and depends on the AMD or Intel CPU. 
# Proxmox uses both but it seems when booting from ZFS it specifically uses SYSTEMD.
# See: https://forum.level1techs.com/t/proxmox-6-2-4-task-error-iommu-not-present-solved/157587/2 
# Enabling IOMMU: https://www.servethehome.com/how-to-pass-through-pcie-nics-with-proxmox-ve-on-intel-and-amd/

- name: Update GRUB to enable iommu at boot - Intel CPU
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on i915.enable_gvt=1"'
  when: is_intel.rc == 0 and _pve_bootloader == 'grub'
  register: update_grub_intel

- name: Update GRUB to enable iommu at boot - AMD CPU
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on"'
  when: is_amd.rc == 0 and _pve_bootloader == 'grub'
  register: update_grub_amd

- name: update-grub
  shell: update-grub
  when: update_grub_intel.changed or update_grub_amd.changed
  register: update_grub

- name: Check presence of iommu in /etc/kernel/cmdline
  command: grep -q 'quiet intel_iommu=on' /etc/kernel/cmdline
  ignore_errors: true
  register: systemd_iommu_configured
  failed_when: systemd == 2

- name: Update /etc/kernel/cmdline to enable iommu - Intel CPU
  lineinfile:
    path: /etc/kernel/cmdline
    backrefs: yes
    regexp: "^(.*boot=.*)$"
    line: '\1 quiet intel_iommu=on'
  when: is_intel.rc == 0 and _pve_bootloader == 'systemd' and systemd_iommu_configured.rc != 0
  register: update_cmdline_intel

- name: Update /etc/kernel/cmdline to enable iommu - AMD CPU
  lineinfile:
    path: /etc/kernel/cmdline
    backrefs: yes
    regexp: "^(.*boot=.*)$"
    line: '\1 quiet amd_iommu=on'
  when: is_amd.rc == 0 and _pve_bootloader == 'systemd' and systemd_iommu_configured.rc != 0
  register: update_cmdline_amd

- name: update boot tool
  shell: proxmox-boot-tool refresh
  when: update_cmdline_intel.changed or update_cmdline_amd.changed
  register: update_proxboot

- name: Register modules for vfio
  lineinfile:
    dest: /etc/modules
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^vfio$', line: 'vfio' }
    - { regexp: '^vfio_iommu_type1', line: 'vfio_iommu_type1' }
    - { regexp: '^vfio_pci', line: 'vfio_pci' }
    - { regexp: '^vfio_virqfd', line: 'vfio_virqfd' }
  register: vfio

- name: Register modules for Intel GPU passthrough (Intel GVT)
  lineinfile:
    dest: /etc/modules
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^kvmgt', line: 'kvmgt' }
    - { regexp: '^exngt', line: 'exngt' }
    - { regexp: '^vfio-mdev', line: 'vfio-mdev' }
  when: is_intel.rc == 0
  register: gvt

- debug: msg="{{ inventory_hostname }} needs reboot"
  when: update_grub.changed or vfio.changed or gvt.changed or update_proxboot.changed
- name: Reboot to apply changes
  reboot:
  when: update_grub.changed or vfio.changed or gvt.changed or update_proxboot.changed

# After reboot please verify:
# IOMMU is enabled: `dmesg | grep -e DMAR -e IOMMU`


# check and update hostname (see: https://pve.proxmox.com/wiki/Renaming_a_PVE_node)
- name: Update hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ inventory_hostname }}.{{ ansible_dns['search'][0] }} {{ inventory_hostname }}"
  register: update_hostname1

- name: Update hostname in /etc/hostname
  lineinfile:
    dest: /etc/hostname
    regexp: ".*"
    line: "{{ inventory_hostname }}"
  register: update_hostname2

- debug: msg="{{ inventory_hostname }} needs reboot after hostname changes"
  when: update_hostname1.changed or update_hostname2.changed
- name: Reboot
  reboot:
  when: update_hostname1.changed or update_hostname2.changed

- name: Enable VLAN aware nic on vmbr0
  lineinfile:
    dest: /etc/network/interfaces
    insertafter: 'bridge-fd 0'
    line: "	bridge-vlan-aware yes"
  notify:
    - restart pve node

- name: Add vmbr1 configuration to /etc/network/interfaces when a second nic is identified
  blockinfile:
    path: /etc/network/interfaces
    block: |
      iface {{ _pve_second_nic }} inet manual

      auto vmbr1
      iface vmbr1 inet static
      	address {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | ipmath(1) }}/24
      	bridge-ports {{ _pve_second_nic }}
      	bridge-stp off
      	bridge-fd 0
      	bridge-vlan-aware yes
      	bridge-vids 2-4094
  when: _pve_second_nic is defined
  notify:
    - restart pve node

- name: Set DNS servers in /etc/resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^nameserver {{ item }}"
    line: "nameserver {{ item }}"
  with_items:
    - "{{ dns }}"

- import_tasks: pve_nfs_attach.yml


# For future, perhaps

# Install ceph packages for pve - https://pve.proxmox.com/wiki/Deploy_Hyper-Converged_Ceph_Cluster
#- name: Proxmox VE Ceph installation
#  shell: pveceph install