---
# Set facts for mgr modules

- name: wait for all mgr to be up
  command: ceph  mgr dump -f json
  register: mgr_dump
  retries: 30
  delay: 5
  changed_when: false
  until:
    - mgr_dump.rc == 0
    - (mgr_dump.stdout | from_json).available | bool

- name: get enabled modules from ceph-mgr
  command: ceph --format json mgr module ls
  check_mode: no
  changed_when: false
  register: _ceph_mgr_modules

- name: set _ceph_mgr_modules fact (convert _ceph_mgr_modules.stdout to a dict)
  set_fact:
    _ceph_mgr_modules: "{{ _ceph_mgr_modules.get('stdout', '{}') | from_json }}"

- name: set _disabled_ceph_mgr_modules fact
  set_fact:
    _disabled_ceph_mgr_modules: "{% if _ceph_mgr_modules.disabled_modules | length == 0 %}[]{% elif _ceph_mgr_modules.disabled_modules[0] | type_debug != 'dict' %}{{ _ceph_mgr_modules['disabled_modules'] }}{% else %}{{ _ceph_mgr_modules['disabled_modules'] | map(attribute='name') | list }}{% endif %}"
