---
# defaults file for proxmox_provision

# Generates random name, but note evertime the variable is called the name is different
vm_name: "{{ lookup('community.general.random_string', upper=false, numbers=false, special=false) }}"

vm_disk_increase: 0     # Increase the vm disk by x GB
vm_start: yes           # Start the VM after it's provisioned
vm_enable_agent: yes    # Enable the proxmox qemu agent