---

- name: Check if data exists already in docker directory {{ docker_dir }}/{{ container_name }}/data
  find:
    paths: "{{ docker_dir }}/{{ container_name }}/data"
    file_type: any
    hidden: true
  register: filesFound

- debug:
      var: filesFound

- name: Copy {{ container_name }} docker data from {{ container_data_backup }}
  become: yes
  ansible.posix.synchronize:
    src: "{{ container_data_backup }}/"
    dest: "{{ docker_dir }}/{{ container_name }}/data"
  delegate_to: "{{ inventory_hostname }}"
  when: filesFound.matched == 0

- name: Create directory {{ ansible_env.HOME }}/scprime
  file:
    path: "{{ ansible_env.HOME }}/scprime"
    state: directory
    recurse: yes

- name: Create docker-compose.yml
  template: src=scprime.j2 dest={{ ansible_env.HOME }}/scprime/docker-compose.yml

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME }}/scprime"
  register: output
