---
- name: Setup WSL environment for Vagrant Hyper-V support
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Vagrant environment variables to ~/.profile
      blockinfile:
        path: ~/.profile
        block: |
          # Enabled Vagrant Hyper-V Provider
          export VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH=/mnt/c/Users/Daz
          export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS=1
          export VAGRANT_DEFAULT_PROVIDER=hyperv
    
    - name: touch /etc/wsl.conf
      file:
        path: "/etc/wsl.conf"
        state: touch
      become: yes
    
    - name: Add wsl.conf to mount windows drvfs with metadata flag
      blockinfile:
        path: /etc/wsl.conf
        block: |
          # Enable extra metadata options by default
          [automount]
          enabled = true
          root = /mnt/
          options = "metadata,umask=77,fmask=11"
          mountFsTab = false
      become: yes


    