---

- name: Do password file
  import_tasks: roles/containers/common/tasks/passwordfile.yml
  
- name: Make sure the {{ container_name }} container is created and running
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "instantlinux/nut-upsd-arm32:latest"
    pull: yes
    state: 'started'
    ports:
      - 3493:3493
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "{{ docker_dir }}/{{ container_name }}/data:/etc/nut"
      - "{{ docker_dir }}/{{ container_name }}/secrets:/run/secrets"
    restart_policy: always