---

# Type of load balancer, eg: http | tcp
haproxy_lb_type: http
haproxy_balance_type: roundrobin
haproxy_frontend_name: my_frontend
haproxy_backend_name: my_backend
haproxy_backend_port: 80
haproxy_frontend_port: "{{ haproxy_backend_port }}"

# Backend servers should point to an Ansible host group name
haproxy_backend_servers: haproxy_hosts
