---
- name: Prepare apt-repositories
  block:
    - name: Install dep package for managing gnupg
      become: yes
      package:
        name: software-properties-common
        state: latest

    - name: Add apt-repository's
      become: yes
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "{{ add_apt_repository }}"
    
  when: add_apt_repository is defined

- name: Update packages
  become: yes
  apt:
    update_cache: yes
    upgrade: "{{ upgrade_packages | bool }}"

- name: Install packages
  become: yes
  package:
    name: "{{ packages }}"
    state: latest
  when: packages | length > 0

- include_tasks: check_reboot.yml
  when: "auto_reboot | bool"
  