---
- name: Update packages
  become: yes
  apt:
    update_cache: yes
    upgrade: "{{ upgrade_packages | bool }}"

- name: Install packages
  become: yes
  package:
    name: "{{ packages }}"
    state: latest
  when: packages | length > 0

- include_tasks: check_reboot.yml
  when: "auto_reboot | bool"
  