---
- include_tasks: essential.yml
  when: "manage_packages | bool"
  tags: packages

- include_tasks: timezone.yaml
  when: "set_timezone | bool"
  tags: tz, timezone

- include_tasks: powersaving.yml
  when: (enable_powersaving | default(False)) and inventory_hostname in groups["baremetal"]
  tags: powersaving

- include_tasks: partition_disk.yaml
  when: partition_devices is defined
  tags: partition

- include_tasks: mounts.yml
  when: mounts is defined
  tags: mounts
