---
- name: Partition the disk into a single large partition filling the disk
  become: yes
  parted:
    device: "{{ item }}"
    number: 1
    state: present
    part_start: "0%"
    part_end: "100%"
    unit: GB
  with_items: "{{ partition_devices }}"

- name: Create filesystem on new partition
  become: yes
  filesystem:
    fstype: "{{ fstype }}"
    dev: "{{ item }}{% if 'nvme' in item %}p{% endif %}1"
  with_items: "{{ partition_devices }}"
