---
# Courtesy of https://github.com/notthebee/infra/tree/main/roles/system

- name: Install the powersaving packages
  become: yes
  package:
    name:
      - powertop 
      #- "linux-tools-{{ ansible_kernel }}"
    state: latest

- name: Install the systemd services
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
    owner: root
    group: root
    mode: 0755
  notify: 
    - powersaving systemd reload
  with_fileglob:
    - files/powersaving/*.service
    - files/powersaving/*.timer
      
- name: Start and enable the systemd services
  become: yes
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  with_items:
    - powertop.timer
    #- cpupower-min.timer