---

container_name: pihole
container_network_ip: ""                # Must be provided
container_network_vlan: 1
container_network_subnet: 192.168.10.0/24
container_network_gateway: 192.168.10.1

# Pihole docker settings
pihole_hostname: pihole2
pihole_upstream_dns1: 192.168.10.1
pihole_upstream_dns2: 8.8.4.4
pihole_webpassword: "{{ infadmin_password }}"

# Pihole gravity sync
pihole_gravity_sync: no
pihole_gravity_sync_direction: "pull"
pihole_gravity_master_host: 'unnas'       # Name of the host in hosts.ini for master PiHole instance
