---

# ganesha package/repo dependancies
nfs_ganesha_packages:
  - nfs-ganesha
  - nfs-ganesha-ceph
  - nfs-ganesha-rados-grace
  - nfs-ganesha-rados-urls
  - nfs-ganesha-rgw
  - ceph-common
  - net-tools
nfs_ganesha_repositories:
  - "ppa:nfs-ganesha/nfs-ganesha-4"
  - "ppa:nfs-ganesha/libntirpc-4"

# ganesha.conf
nfs_ganesha_cluster_recovery_backend: "rados_cluster"
nfs_ganesha_ceph_conf: "{{ default_ceph_conf }}"
nfs_ganesha_ceph_admin_userid: admin
nfs_ganesha_ganesha_conf: /etc/ganesha/ganesha.conf
nfs_ganesha_rados_url: "rados://{{ pve_ceph_rados_nfs_pool }}/{{ pve_ceph_rados_nfs_pool_ganesha_namespace }}/{{ nfs_ganesha_rados_export }}"
