- name: Add Vagrant environment variables to ~/.profile
  blockinfile:
    path: ~/.profile
    block: |
      # Enabled Vagrant Hyper-V Provider
      export VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH=/mnt/c/Users/Daz
      export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS=1
      export VAGRANT_DEFAULT_PROVIDER=hyperv

- name: Check /etc/wsl.conf exists
  stat:
    path: /etc/wsl.conf
  register: stat_result

- name: touch /etc/wsl.conf
  file:
    path: "/etc/wsl.conf"
    state: touch
  when: not stat_result.stat.exists
  become: yes

- name: Add wsl.conf to mount windows drvfs with metadata flag
  blockinfile:
    path: /etc/wsl.conf
    block: |
      # Enable extra metadata options by default
      [automount]
      enabled = true
      root = /mnt/
      options = "metadata,umask=77,fmask=11"
      mountFsTab = false
  become: yes