---

- name: Check if data exists already in docker directory {{ docker_dir }}/{{ container_name }}/data
  find:
    paths: "{{ docker_dir }}/{{ container_name }}/data"
    file_type: any
    hidden: true
  register: filesFound

- debug:
      var: filesFound

- name: Copy {{ container_name }} docker data from {{ container_data_backup }}
  become: yes
  ansible.posix.synchronize:
    src: "{{ container_data_backup }}/"
    dest: "{{ docker_dir }}/{{ container_name }}/data"
  delegate_to: "{{ inventory_hostname }}"
  when: filesFound.matched == 0
