---
# Configures a secrets file with your filename under {{ docker_dir }}/{{ container_name }}/secrets

- name: Create {{ container_name }} secrets folder
  become: yes
  file:
    path: "{{ docker_dir }}/{{ container_name }}/secrets"
    state: directory
    recurse: yes

- name: Get stat {{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}
  stat:
    path: "{{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}"
  register: p

- name: Ensure {{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }} file is created
  become: yes
  file:
    path: "{{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}"
    owner: root
    group: root
    mode: '0600'
    state: touch
  when: p.stat.exists is defined and not p.stat.exists

- name: Fetch existing password from {{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}
  become: yes
  slurp:
    src: "{{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}"
  register: current_password

- name: Store container_password into {{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}
  become: yes
  shell: echo -n {{ container_password }} > {{ docker_dir }}/{{ container_name }}/secrets/{{ password_file }}
  when: current_password.content | b64decode != container_password