---
# See: https://wiki.spacefarmers.io/guides/farming/backupdb

- block:
  - name: Install sqlite package
    become: yes
    package:
      name:
        - sqlite 
      state: latest

  - name: Install the systemd services
    become: yes
    template:
      src: "{{ item }}"
      dest: "/etc/systemd/system/{{ item | basename | replace('chia', outer_item['name']) }}"
      owner: root
      group: root
      mode: 0755
    notify: 
      - blockchain-backup systemd reload
    with_fileglob:
      - files/blockchain-backup/*.service
      - files/blockchain-backup/*.timer
        
  - name: Start and enable the systemd services
    become: yes
    systemd:
      state: started
      enabled: true
      name: "{{ item }}"
    with_items:
      - "{{ outer_item['name'] }}-blockchain-backup.timer"

  when: "outer_item['blockchain_db_backup'] is defined and outer_item['blockchain_db_backup'] | bool"
