---

- name: Set blockchain backup var
  set_fact:
    chia_blockchain_db_dir: "{{ chia_machinaris_data }}/.machinaris{% if outer_item['name'] != 'chia' %}-{{ outer_item['name'] }}{% endif %}/mainnet/db"

- import_tasks: chia_blockchain_db.yaml

# Setup chia containers variable
- import_tasks: chia_compose_container_vars.yaml

# Setup backup of blockchain DB and machinaris data
- import_tasks: chia_blockchain_backup.yaml
- import_tasks: chia_machinaris_backup.yaml
