---

# Ceph networks
pve_ceph_net_front_base: "{{ pve_ceph_network_frontend['subnet'] | regex_replace('/[0-9]{2}','') }}"
pve_ceph_net_front_cidr: "{{ pve_ceph_network_frontend['subnet'] | regex_replace('^(.*)/','') }}"
pve_ceph_net_back_base: "{{ pve_ceph_network_backend['subnet'] | regex_replace('/[0-9]{2}','') }}"
pve_ceph_net_back_cidr: "{{ pve_ceph_network_backend['subnet'] | regex_replace('^(.*)/','') }}"

# Ceph daemons to be gracefully failed (see pve_reboot_graceful.yml)
pve_ceph_daemons_fail:
  - mgr
  - mds

# Ceph packages to be installed
pve_ceph_packages: ['ceph', 'ceph-common', 'ceph-mds', 'ceph-fuse', 'ceph-mgr-dashboard', 'gdisk', 'ceph-mgr-diskprediction-local']
