- name: powersaving systemd reload
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{ item }}"
  with_items:
    - powertop
    - powertop.timer
    #- cpupower-min
    #- cpupower-min.timer

- name: reboot
  become: yes
  reboot:
  when: "auto_reboot | bool"