---

chia_harvester_plots:
  - /mnt/truenas01/data00
  - /mnt/truenas01/data10
  - /mnt/storecrypt/data0

# List the blockchains this host will use
chia_blockchains:
  - name: chia
    ip: 192.168.15.20   # update chia.yaml -> machinaris_controller if this address changes
    gpu: nvidia
    blockchain_db_backup: yes
    machinaris_backup: yes
    disable_plot_check: yes
    restore_blockchain_db: yes

host_packages:
  - nvtop
  - nvidia-driver-535               # https://forums.developer.nvidia.com/t/nvidia-smi-not-working-on-dual-booted-ubuntu-20-04/262433

  # NFS mounts for chia network data shares
host_mounts:
  - { path: /mnt/truenas01/data00, src: "{{ chia_network['truenas01']['ip'] }}:/mnt/pool0/data0", fstype: nfs, opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800' }
  - { path: /mnt/truenas01/data10, src: "{{ chia_network['truenas01']['ip'] }}:/mnt/pool1/data0", fstype: nfs, opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800' }
  - { path: /mnt/storecrypt/data0, src: "{{ hostvars['storecrypt'].ansible_host }}:/pool0/data0", fstype: nfs, opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800' }
