---

chia_harvester_plots:
  - /mnt/truenas01/data00
  #- /mnt/truenas01/data10
  - /mnt/storecrypt/data0

# List the blockchains this host will use
chia_blockchains:
  - name: chia
    ip: 192.168.15.20
    gpu: nvidia
