---
persistent_backup: "{{ backup_local_mountpoint }}"

filesystem_mounts:
  - { path: "{{ persistent_backup }}", src: "{{ backup_server }}:{{ backup_server_export }}", fstype: nfs, opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800' }
