---
pve_second_nic_regex: "^enp122s0"

# Default storage location for VM's on this node
vm_storage_default: 'local-nvme'

# k3s_worker_pcie:
#   - "08:00.0"       # 2TB Sabrent Rocket 4.0 NVMe - Non-Volatile memory controller: Phison Electronics Corporation E16 PCIe4 NVMe Controller (rev 01)
#   - id: "00:02.0"   # Intel Corporation CometLake-S GT2 [UHD Graphics 630]
#     mdev: "i915-GVTg_V5_4"

k3s_worker_node_storage: "{{ vm_storage_default }}"

k3s_worker_virtual_disk:
  - '{{ vm_storage_default }}:931.53,format=raw'        # Create 1TB disk for k3s longhorn on 'local-nvme' storage; 931.53 is GiB as close as possible to 1TB NVME

#k3s_worker_disk_passthrough:
#  - ata-#############-####_########

k3s_worker_node_memory: 16384
k3s_worker_node_memory_min: 8192
k3s_worker_node_cpu: 12
