---
k3s_worker_pcie:
  - "02:00.0"   # 1TB Samsung 970 EVO NVMe - Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
  - "00:02.0"   # Intel Corporation CometLake-S GT2 [UHD Graphics 630]

k3s_worker_node_memory: 36864
k3s_worker_node_cpu: 6
