---
k3s_worker_pcie:
  - "02:00.0"       # 1TB Samsung 970 EVO NVMe - Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
  - id: "00:02.0"   # Intel Corporation CometLake-S GT2 [UHD Graphics 630]
    mdev: "i915-GVTg_V5_4"

k3s_worker_disk_passthrough:
  - ata-ST4000VN000-1H4168_Z3054BCQ
  - ata-ST4000VN008-2DR166_ZDHAQJG9

k3s_worker_node_memory: 32768
k3s_worker_node_memory_min: 16384
k3s_worker_node_cpu: 6
