---
# Default storage location for VM's on this node
vm_storage_default: 'local-nvme'

k3s_worker_pcie:
  # - "02:00.0"       # 1TB Samsung 970 EVO NVMe - Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
  - id: "00:02.0"   # Intel Corporation CometLake-S GT2 [UHD Graphics 630]
    mdev: "i915-GVTg_V5_4"

k3s_worker_node_storage: "{{ vm_storage_default }}"

k3s_worker_virtual_disk:
  - '{{ vm_storage_default }}:931.53,format=raw'        # Create 1TB disk for k3s longhorn on 'local-nvme' storage; 931.53 is GiB as close as possible to 1TB NVME

k3s_worker_disk_passthrough:
  - ata-ST4000VN000-1H4168_Z301G8TD
  - ata-ST4000VN008-2DR166_ZGY9DPR1

k3s_worker_node_memory: 16384
k3s_worker_node_memory_min: 8192
k3s_worker_node_cpu: 6


# ZFS ARC cache uses 50% of RAM by default. As this server hosts VM's configured for 75% of system RAM (48GB), ARC cache has been reduced.
# 
# ```
# vi /etc/modprobe.d/zfs.conf -> Enter: `options zfs zfs_arc_max=17179869184` (16GB)
# update-initramfs -u <-- required to apply
# reboot
# Check change has worked with `arc_summary` or `arc_summary | grep "ARC size (current)"`
# ```
# See:  https://www.reddit.com/r/Proxmox/comments/14ka64x/how_to_reduce_memory_used_by_zfs/
#       https://pve.proxmox.com/wiki/ZFS:_Tips_and_Tricks#Install_on_a_high_performance_system 
