---
pve_second_nic_regex: "^enp122s0"

# Default storage location for VM's on this node
vm_storage_default: 'local-nvme'

k3s_worker_pcie:
  - "08:00.0"       # 2TB Sabrent Rocket 4.0 NVMe - Non-Volatile memory controller: Phison Electronics Corporation E16 PCIe4 NVMe Controller (rev 01)
#   - id: "00:02.0"   # Intel Corporation CometLake-S GT2 [UHD Graphics 630]
#     mdev: "i915-GVTg_V5_4"

k3s_worker_node_memory: 16384
k3s_worker_node_memory_min: 8192
k3s_worker_node_cpu: 12
k3s_worker_node_storage: "{{ vm_storage_default }}"
