---
# vars file for ansible-role-proxmox
pve_base_dir: "/etc/pve"
pve_cluster_conf: "{{ pve_base_dir }}/corosync.conf"

# NFS shares to mount on pve nodes
nfs:
  - name: ISO
    host: "{{ hostvars['unnas'].ansible_host }}"
    path: /mnt/user/ISO/proxmox