---
- name: Set timezone to "{{ timezone }}"
  shell: timedatectl set-timezone "{{ timezone }}"

- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages for maas role
  package:
    name: "{{ packages }}"
    state: latest