---

- import_tasks: load_variables.yml

- import_tasks: ssh_cluster_config.yml
  when:
    - "pve_manage_ssh | bool and pve_cluster_enabled | bool"
  tags: cluster

- import_tasks: pve_cluster_config.yml
  when: "pve_cluster_enabled | bool"
  tags: cluster

- import_tasks: pve_templates.yml
  when: _pve_local_storage is defined
  tags: templates
