---

- name: Update packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists

- name: Check timezone
  shell: cat /etc/timezone
  register: current_timezone
  changed_when: "timezone not in current_timezone.stdout"

- name: Set timezone {{ timezone }}
  copy: content={{ timezone }}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  when: current_timezone.stdout != timezone
  notify:
  - Update timezone

# Dietpi scripted functions:

- import_tasks: change_hostname.yml
  when: ansible_hostname != inventory_hostname

- import_tasks: dietpi-set_userdata.yml
  when: dietpi_change_hostname != ""
